# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCUK0E-e8W1ouC-oqfTs1DeKDUJ1Kype
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,marker='x')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,marker='+',ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y, marker='x',ms=20,mec='g')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1=np.array([0,3,9,13])
y1=np.array([1,4,6,8])
x2=np.array([0,2,4,6])
y2=np.array([1,3,5,7])

plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,5,10,15,20,25])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,5,10,15,20,25])
plt.scatter(x,y,color='black')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,5,10,15,20,25])
mycolor=['green','blue','red','lime','yellow','black']

plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,5,10,15,20,25])
mycolor=['green','blue','red','lime','yellow','black']
size=[20,30,40,50,60,70]

plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['614-23','510-23','613-23'])
y=np.array([23,18,20])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([23,18,20])
plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
mylabes=["614-23","510-23","613-23"]
x=np.array([23,18,20])
plt.pie(x,labels=mylabes)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
mylabes=["614-23","510-23","613-23"]
x=np.array([23,18,20])
myexplode=[0.3,0,0]
plt.pie(x,labels=mylabes,startangle=80,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
mylabes=["614-23","510-23","613-23"]
mycolors=["black","pink","aqua"]
x=np.array([23,18,20])
myexplode=[0.3,0,0]
plt.pie(x,labels=mylabes,startangle=80,explode=myexplode,colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
mylabes=["614-23","510-23","613-23"]
mycolors=["black","pink","aqua"]
x=np.array([23,18,20])
plt.pie(x,labels=mylabes)
plt.legend(title='Nomi:')
plt.show()